export const LOAD_RECIPES = "LOAD_RECIPES";
export const LOAD_MORE_RECIPES = "LOAD_MORE_RECIPES";
export const ADD_FILTER = "ADD_FILTER";
export const REMOVE_FILTER = "REMOVE_FILTER";
export const REMOVE_ALL_FILTERS = "REMOVE_ALL_FILTERS";
export const UPDATE_RECIPES = "UPDATE_RECIPES";
export const UPDATE_FILTERS = "UPDATE_FILTERS";

export const USER_CREATE = "USER_CREATE";
export const USER_LOAD = "USER_LOAD";
export const USER_LOGIN = "USER_LOGIN";
export const USER_OAUTH = "USER_OAUTH";
export const USER_OAUTH_CALLBACK = "USER_OAUTH_CALLBACK";
export const USER_FORGOT_PASSWORD = "USER_FORGOT_PASSWORD";
export const USER_RESET_PASSWORD = "USER_RESET_PASSWORD";

export const USER_SAVE_RECIPE = "USER_SAVE_RECIPE";
export const USER_DELETE_RECIPE = "USER_DELETE_RECIPE";
export const USER_GET_RECIPES = "USER_GET_RECIPES";

export const USER_SAVE_PRODUCT = "USER_SAVE_PRODUCT";
export const USER_UPDATE_PRODUCT = "USER_UPDATE_PRODUCT";
export const USER_DELETE_PRODUCT = "USER_DELETE_PRODUCT";
export const USER_GET_PRODUCTS = "USER_GET_PRODUCTS";

export const REQUEST = "_REQUEST";
export const SUCCESS = "_SUCCESS";
export const FAILURE = "_FAILURE";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
